(() => {
  "use strict";
  const { VALUATION_BASES, calculateAsset, summarizePortfolio } = window.MercuryPortfolio;
  const $ = (selector) => document.querySelector(selector);
  const currency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
  const preciseCurrency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const percentage = new Intl.NumberFormat("en-US", { style: "percent", maximumFractionDigits: 1 });
  const categoryNames = { "domestic-equity": "Domestic equity", "international-equity": "International equity", bonds: "Bonds", crypto: "Crypto", cash: "Cash", other: "Other" };
  const chartColors = ["#008f89", "#49bfb9", "#83d0cb", "#b7e2dc", "#d4ece7", "#6a7a79"];
  const state = { client: null, user: null, account: null, holdings: [], quotes: [], snapshots: [], charts: {}, preview: false, pendingQuote: null };

  const sampleHoldings = [
    { id: "preview-total", symbol: "VT", name: "Global equity fund", instrument_type: "etf", allocation_category: "domestic-equity", valuation_basis: "shares-and-price", shares: 180, manual_price_cents: null, expected_annual_return_rate: 0.07, distribution_yield_rate: 0.018, target_allocation_rate: 0.42, weekly_contribution_rate: 0.4, dividend_policy: "reinvest", capital_gains_policy: "reinvest", custom_policy_note: null },
    { id: "preview-international", symbol: "VXUS", name: "International equity", instrument_type: "etf", allocation_category: "international-equity", valuation_basis: "shares-and-price", shares: 320, manual_price_cents: null, expected_annual_return_rate: 0.06, distribution_yield_rate: 0.026, target_allocation_rate: 0.25, weekly_contribution_rate: 0.25, dividend_policy: "reinvest", capital_gains_policy: "reinvest", custom_policy_note: null },
    { id: "preview-bond", symbol: "BND", name: "Total bond market", instrument_type: "etf", allocation_category: "bonds", valuation_basis: "shares-and-price", shares: 420, manual_price_cents: null, expected_annual_return_rate: 0.04, distribution_yield_rate: 0.042, target_allocation_rate: 0.23, weekly_contribution_rate: 0.25, dividend_policy: "transfer-to-bank", capital_gains_policy: "hold-cash", custom_policy_note: null },
    { id: "preview-cash", symbol: null, name: "Cash reserve", instrument_type: "cash", allocation_category: "cash", valuation_basis: "manual-value", manual_value_cents: 250000, manual_price_cents: null, shares: null, expected_annual_return_rate: 0.035, distribution_yield_rate: 0.035, target_allocation_rate: 0.1, weekly_contribution_rate: 0.1, dividend_policy: "hold-cash", capital_gains_policy: null, custom_policy_note: null },
  ];
  const sampleQuotes = [
    { holding_id: "preview-total", price_cents: 12625, previous_close_cents: 12560, source: "Sample data", as_of: "2026-08-30T20:30:00.000Z" },
    { holding_id: "preview-international", price_cents: 6790, previous_close_cents: 6825, source: "Sample data", as_of: "2026-08-30T20:30:00.000Z" },
    { holding_id: "preview-bond", price_cents: 7265, previous_close_cents: 7275, source: "Sample data", as_of: "2026-08-30T20:30:00.000Z" },
  ];
  const sampleSnapshots = [{ snapshot_date: "2026-08-27", total_value_cents: 680200 }, { snapshot_date: "2026-08-28", total_value_cents: 688100 }, { snapshot_date: "2026-08-29", total_value_cents: 691500 }, { snapshot_date: "2026-08-30", total_value_cents: 695170 }];

  function cents(value) { return value === null || value === undefined || value === "" ? null : Math.round(Number(value) * 100); }
  function rate(value) { return value === null || value === undefined || value === "" ? null : Number(value) / 100; }
  function dateLabel(value) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", timeZone: "America/New_York" }).format(new Date(value)); }
  function latestQuotes() { return state.quotes.reduce((memo, quote) => (!memo[quote.holding_id] || new Date(quote.as_of) > new Date(memo[quote.holding_id].as_of) ? { ...memo, [quote.holding_id]: quote } : memo), {}); }
  function holdingAsset(holding) {
    const quote = latestQuotes()[holding.id];
    const automaticPrice = quote?.price_cents ?? holding.manual_price_cents;
    return {
      id: holding.id, symbol: holding.symbol, name: holding.name, assetType: holding.name || holding.symbol || "Asset", instrumentType: holding.instrument_type, allocationCategory: holding.allocation_category,
      valuationBasis: holding.valuation_basis, manualValueCents: holding.manual_value_cents, shares: holding.shares === null ? null : Number(holding.shares), unitPriceCents: automaticPrice,
      quoteSource: quote?.source || (holding.manual_price_cents !== null ? "Manual price" : null), quoteAsOf: quote?.as_of || null, priorCloseCents: quote?.previous_close_cents ?? null,
      expectedAnnualReturnRate: holding.expected_annual_return_rate === null ? null : Number(holding.expected_annual_return_rate), distributionYieldRate: holding.distribution_yield_rate === null ? null : Number(holding.distribution_yield_rate), targetAllocationRate: holding.target_allocation_rate === null ? null : Number(holding.target_allocation_rate), weeklyContributionRate: holding.weekly_contribution_rate === null ? null : Number(holding.weekly_contribution_rate), dividendPolicy: holding.dividend_policy, capitalGainsPolicy: holding.capital_gains_policy, customPolicyNote: holding.custom_policy_note,
    };
  }
  function portfolio() {
    const assets = state.holdings.map(holdingAsset).filter((asset) => asset.valuationBasis === VALUATION_BASES.MANUAL_VALUE || asset.unitPriceCents !== null);
    return summarizePortfolio(assets, { weeklyContributionCents: state.account?.weekly_contribution_cents || 0 });
  }
  function formatSigned(value) { return `${value > 0 ? "+" : value < 0 ? "−" : ""}${currency.format(Math.abs(value || 0))}`; }
  function setText(selector, value) { $(selector).textContent = value; }
  function chart(id, config) { if (state.charts[id]) state.charts[id].destroy(); state.charts[id] = new window.Chart($(id), config); }
  function chartOptions() { return { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false }, tooltip: { callbacks: { label: (context) => `${context.label || ""}: ${currency.format(context.raw)}` } } }, scales: { x: { grid: { display: false }, ticks: { color: "#566260" } }, y: { grid: { color: "rgba(33,44,42,.12)" }, ticks: { color: "#566260", callback: (value) => currency.format(value) } } } }; }
  function renderCharts(summary) {
    const rows = summary.rows.slice().sort((a, b) => b.marketValueCents - a.marketValueCents);
    const values = rows.map((row) => row.marketValueCents / 100);
    chart("value-chart", { type: "bar", data: { labels: rows.map((row) => row.asset.symbol || row.asset.name), datasets: [{ data: values, backgroundColor: chartColors, borderRadius: 3 }] }, options: chartOptions() });
    setText("#value-chart-summary", rows.map((row) => `${row.asset.symbol || row.asset.name} ${currency.format(row.marketValueCents / 100)}`).join(", "));
    const allocations = rows.reduce((memo, row) => ({ ...memo, [row.asset.allocationCategory]: (memo[row.asset.allocationCategory] || 0) + row.marketValueCents / 100 }), {});
    chart("allocation-chart", { type: "doughnut", data: { labels: Object.keys(allocations).map((key) => categoryNames[key]), datasets: [{ data: Object.values(allocations), backgroundColor: chartColors, borderWidth: 0 }] }, options: { responsive: true, maintainAspectRatio: false, cutout: "68%", plugins: { legend: { position: "bottom", labels: { boxWidth: 10, usePointStyle: true, color: "#303a38" } } } } });
    setText("#allocation-chart-summary", Object.entries(allocations).map(([key, value]) => `${categoryNames[key]} ${currency.format(value)}`).join(", "));
    const incomeRows = rows.filter((row) => row.estimatedAnnualIncomeCents !== null && row.estimatedAnnualIncomeCents > 0);
    chart("income-chart", { type: "bar", data: { labels: incomeRows.map((row) => row.asset.symbol || row.asset.name), datasets: [{ data: incomeRows.map((row) => row.estimatedAnnualIncomeCents / 100), backgroundColor: chartColors, borderRadius: 3 }] }, options: chartOptions() });
    setText("#income-chart-summary", incomeRows.map((row) => `${row.asset.symbol || row.asset.name} ${currency.format(row.estimatedAnnualIncomeCents / 100)}`).join(", "));
    const snapshots = [...state.snapshots].sort((a, b) => a.snapshot_date.localeCompare(b.snapshot_date));
    $("#history-empty").hidden = snapshots.length >= 2; $("#history-chart").hidden = snapshots.length < 2;
    if (snapshots.length >= 2) { chart("history-chart", { type: "line", data: { labels: snapshots.map((entry) => dateLabel(entry.snapshot_date)), datasets: [{ data: snapshots.map((entry) => entry.total_value_cents / 100), borderColor: "#008f89", backgroundColor: "rgba(0,143,137,.12)", fill: true, pointRadius: 3, tension: .35 }] }, options: chartOptions() }); setText("#history-chart-summary", snapshots.map((entry) => `${dateLabel(entry.snapshot_date)} ${currency.format(entry.total_value_cents / 100)}`).join(", ")); }
  }
  function policyLabel(value) { return value ? value.replaceAll("-", " ") : "—"; }
  function renderTable(summary) {
    const quoteByHolding = latestQuotes();
    $("#holdings-body").replaceChildren(...summary.rows.map((row) => {
      const holding = state.holdings.find((entry) => entry.id === row.asset.id); const quote = quoteByHolding[row.asset.id]; const tr = document.createElement("tr");
      const price = row.asset.valuationBasis === VALUATION_BASES.MANUAL_VALUE ? "Manual value" : row.asset.unitPriceCents === null ? "Needs price" : preciseCurrency.format(row.asset.unitPriceCents / 100);
      const asOf = quote?.as_of ? `As of ${dateLabel(quote.as_of)}` : row.asset.quoteSource || "Manual";
      tr.innerHTML = `<th scope="row"><strong>${row.asset.symbol || "—"}</strong><small>${row.asset.name || ""}</small></th><td>${row.asset.instrumentType.replaceAll("-", " ")}<small>${categoryNames[row.asset.allocationCategory]}</small></td><td>${price}<small>${asOf}</small></td><td>${row.asset.expectedAnnualReturnRate === null ? "—" : percentage.format(row.asset.expectedAnnualReturnRate)}</td><td class="${row.dayChangeCents < 0 ? "is-negative" : row.dayChangeCents > 0 ? "is-positive" : ""}">${row.dayChangeCents === null ? "—" : `${formatSigned(row.dayChangeCents / 100)} ${row.dayChangeRate === null ? "" : percentage.format(row.dayChangeRate)}`}</td><td>${row.asset.shares === null ? "—" : Number(row.asset.shares).toLocaleString()}</td><td><strong>${currency.format(row.marketValueCents / 100)}</strong></td><td>${row.asset.distributionYieldRate === null ? "—" : percentage.format(row.asset.distributionYieldRate)}</td><td>${row.estimatedAnnualIncomeCents === null ? "—" : currency.format(row.estimatedAnnualIncomeCents / 100)}<small>${policyLabel(row.asset.dividendPolicy)}</small></td><td>${row.allocationRate === null ? "—" : percentage.format(row.allocationRate)}</td><td>${row.asset.targetAllocationRate === null ? "—" : percentage.format(row.asset.targetAllocationRate)}</td><td>${row.weeklyContributionCents === null ? "—" : currency.format(row.weeklyContributionCents / 100)}</td><td><button class="brokerage-row-action" type="button" data-edit-id="${holding.id}" aria-label="Edit ${row.asset.symbol || row.asset.name}"><i class="fa-solid fa-pen" aria-hidden="true"></i></button></td>`;
      return tr;
    }));
    $("#holdings-total").innerHTML = `<tr><th scope="row" colspan="6">Portfolio</th><td>${currency.format(summary.totalMarketValueCents / 100)}</td><td></td><td>${currency.format(summary.totalEstimatedAnnualIncomeCents / 100)}</td><td>${summary.targetAllocationRate === null ? "—" : percentage.format(summary.targetAllocationRate)}</td><td></td><td>${currency.format(summary.totalWeeklyContributionCents / 100)}</td><td></td></tr>`;
    document.querySelectorAll("[data-edit-id]").forEach((button) => button.addEventListener("click", () => openAsset(state.holdings.find((holding) => holding.id === button.dataset.editId))));
  }
  function render() {
    const summary = portfolio();
    setText("#metric-value", currency.format(summary.totalMarketValueCents / 100)); setText("#metric-income", currency.format(summary.totalEstimatedAnnualIncomeCents / 100)); setText("#metric-weekly", currency.format(summary.totalWeeklyContributionCents / 100));
    setText("#metric-day", summary.totalDayChangeCents === null ? "—" : `${formatSigned(summary.totalDayChangeCents / 100)} · ${percentage.format(summary.totalDayChangeRate)}`); $("#metric-day").className = summary.totalDayChangeCents < 0 ? "is-negative" : summary.totalDayChangeCents > 0 ? "is-positive" : "";
    setText("#metric-day-note", summary.dayChangeCoverage === "complete" ? "Compared with prior close" : "Some holdings need a prior close"); setText("#portfolio-warnings", summary.warnings.join(" "));
    renderCharts(summary); renderTable(summary); $("#main-content").setAttribute("aria-busy", "false");
  }
  function getFormValue(form, key) { const value = new FormData(form).get(key); return value === "" ? null : value; }
  function toggleValuationFields() { const manual = getFormValue($("#asset-form"), "valuationBasis") === "manual-value"; $("#manual-price-field").hidden = manual; $("#manual-value-field").hidden = !manual; $("#asset-shares").required = !manual; }
  function openAsset(holding) {
    const form = $("#asset-form"); form.reset(); state.pendingQuote = null; $("#quote-form-status").textContent = ""; $("#asset-dialog-title").textContent = holding ? "Edit asset" : "Add asset";
    if (holding) { const set = (id, value) => { if (value !== null && value !== undefined) $(id).value = value; }; set("#asset-id", holding.id); set("#asset-symbol", holding.symbol); set("#asset-name", holding.name); set("#asset-instrument", holding.instrument_type); set("#asset-category", holding.allocation_category); set("#asset-shares", holding.shares); set("#asset-return", holding.expected_annual_return_rate === null ? null : Number(holding.expected_annual_return_rate) * 100); set("#asset-yield", holding.distribution_yield_rate === null ? null : Number(holding.distribution_yield_rate) * 100); set("#asset-target", holding.target_allocation_rate === null ? null : Number(holding.target_allocation_rate) * 100); set("#asset-weekly", holding.weekly_contribution_rate === null ? null : Number(holding.weekly_contribution_rate) * 100); set("#asset-dividend-policy", holding.dividend_policy); set("#asset-gains-policy", holding.capital_gains_policy); set("#asset-policy-note", holding.custom_policy_note); set("#asset-manual-price", holding.manual_price_cents === null ? null : holding.manual_price_cents / 100); set("#asset-manual-value", holding.manual_value_cents === null ? null : holding.manual_value_cents / 100); form.querySelector(`[name="valuationBasis"][value="${holding.valuation_basis}"]`).checked = true; }
    toggleValuationFields(); $("#asset-dialog").showModal();
  }
  async function sessionToken() { const { data } = await state.client.auth.getSession(); return data.session?.access_token; }
  async function requestQuote(symbol, instrumentType) { const token = await sessionToken(); const response = await fetch(`/api/portfolio/quotes?symbol=${encodeURIComponent(symbol)}&instrumentType=${encodeURIComponent(instrumentType)}`, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Quote lookup failed."); return data; }
  async function lookupQuote() { const symbol = $("#asset-symbol").value.trim(); const instrumentType = $("#asset-instrument").value; if (!symbol) return setText("#quote-form-status", "Enter a symbol before looking up a price."); if (state.preview) return setText("#quote-form-status", "Sample workspace cannot call a provider. Enter a manual price to preview the calculation."); setText("#quote-form-status", "Looking up price…"); try { state.pendingQuote = await requestQuote(symbol, instrumentType); $("#asset-manual-price").value = (state.pendingQuote.priceCents / 100).toFixed(2); setText("#quote-form-status", `${preciseCurrency.format(state.pendingQuote.priceCents / 100)} from Twelve Data. As of ${dateLabel(state.pendingQuote.asOf)}.`); } catch (error) { setText("#quote-form-status", `${error.message} You can enter a manual authoritative price or total value.`); } }
  function formHolding() {
    const form = $("#asset-form"); const valuationBasis = getFormValue(form, "valuationBasis"); const custom = getFormValue(form, "customPolicyNote");
    const holding = { id: getFormValue(form, "id") || crypto.randomUUID(), account_id: state.account?.id || "preview", symbol: getFormValue(form, "symbol")?.toUpperCase() || null, name: getFormValue(form, "name"), instrument_type: getFormValue(form, "instrumentType"), allocation_category: getFormValue(form, "allocationCategory"), valuation_basis: valuationBasis, shares: valuationBasis === "shares-and-price" ? Number(getFormValue(form, "shares")) : null, manual_value_cents: valuationBasis === "manual-value" ? cents(getFormValue(form, "manualValue")) : null, manual_price_cents: valuationBasis === "shares-and-price" ? cents(getFormValue(form, "manualPrice")) : null, expected_annual_return_rate: rate(getFormValue(form, "expectedAnnualReturn")), distribution_yield_rate: rate(getFormValue(form, "distributionYield")), target_allocation_rate: rate(getFormValue(form, "targetAllocation")), weekly_contribution_rate: rate(getFormValue(form, "weeklyAllocation")), dividend_policy: getFormValue(form, "dividendPolicy"), capital_gains_policy: getFormValue(form, "capitalGainsPolicy"), custom_policy_note: custom };
    if (!holding.symbol && !holding.name) throw new Error("Add a symbol or a name."); if (valuationBasis === "shares-and-price" && (!Number.isFinite(holding.shares) || holding.shares < 0)) throw new Error("Shares are required for a price-based value."); if (valuationBasis === "manual-value" && holding.manual_value_cents === null) throw new Error("A manual total value is required."); if ((holding.dividend_policy === "custom" || holding.capital_gains_policy === "custom") && !custom) throw new Error("A policy note is required for a custom policy."); if (valuationBasis === "shares-and-price" && holding.manual_price_cents === null && !state.pendingQuote) throw new Error("Look up a quote or enter a manual price."); return holding;
  }
  async function saveAsset(event) { event.preventDefault(); const save = $("#save-asset"); try { save.disabled = true; save.textContent = "Saving…"; const holding = formHolding(); if (state.preview) { const index = state.holdings.findIndex((entry) => entry.id === holding.id); if (index >= 0) state.holdings[index] = holding; else state.holdings.push(holding); if (state.pendingQuote) state.quotes = [...state.quotes.filter((quote) => quote.holding_id !== holding.id), { holding_id: holding.id, price_cents: state.pendingQuote.priceCents, previous_close_cents: state.pendingQuote.priorCloseCents, source: "Sample quote", as_of: state.pendingQuote.asOf }]; $("#asset-dialog").close(); render(); setText("#data-status", "Sample workspace updated. Configure private sync before entering real data."); return; }
      const { error } = await state.client.from("holdings").upsert(holding); if (error) throw error; if (state.pendingQuote) { const { error: quoteError } = await state.client.from("holding_quotes").upsert({ holding_id: holding.id, price_cents: state.pendingQuote.priceCents, previous_close_cents: state.pendingQuote.priorCloseCents, source: state.pendingQuote.source, as_of: state.pendingQuote.asOf }, { onConflict: "holding_id,as_of" }); if (quoteError) throw quoteError; } $("#asset-dialog").close(); await loadData(); setText("#data-status", "Saved to your private Brokerage account.");
    } catch (error) { setText("#quote-form-status", error.message || "This asset could not be saved."); } finally { save.disabled = false; save.textContent = "Save asset"; } }
  async function loadData() { const [holdings, quotes, snapshots] = await Promise.all([state.client.from("holdings").select("*").eq("account_id", state.account.id).order("created_at"), state.client.from("holding_quotes").select("*").order("as_of", { ascending: false }), state.client.from("portfolio_snapshots").select("*").eq("account_id", state.account.id).order("snapshot_date")]); if (holdings.error) throw holdings.error; state.holdings = holdings.data; state.quotes = quotes.data || []; state.snapshots = snapshots.data || []; render(); }
  async function ensureAccount() { const existing = await state.client.from("accounts").select("*").eq("account_type", "brokerage").maybeSingle(); if (existing.error) throw existing.error; if (existing.data) return existing.data; const created = await state.client.from("accounts").insert({ name: "Brokerage", account_type: "brokerage" }).select().single(); if (created.error) throw created.error; return created.data; }
  async function refreshPrices() { if (state.preview) return setText("#data-status", "Sample data has no live price connection. Configure Twelve Data to refresh quotes."); const holdings = state.holdings.filter((holding) => holding.valuation_basis === "shares-and-price" && holding.symbol); setText("#data-status", `Refreshing ${holdings.length} price${holdings.length === 1 ? "" : "s"}…`); for (const holding of holdings) { try { const quote = await requestQuote(holding.symbol, holding.instrument_type); await state.client.from("holding_quotes").upsert({ holding_id: holding.id, price_cents: quote.priceCents, previous_close_cents: quote.priorCloseCents, source: quote.source, as_of: quote.asOf }, { onConflict: "holding_id,as_of" }); } catch (error) { setText("#data-status", `${error.message} Last successful quotes remain in place.`); } } await loadData(); setText("#data-status", "Prices refreshed. Last successful provider values are retained if a lookup fails."); }
  async function refreshHistory() { if (state.preview) return setText("#data-status", "History refresh needs the private snapshot service. Sample snapshots remain visible."); const token = await sessionToken(); const response = await fetch("/api/portfolio/snapshot", { method: "POST", headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok) return setText("#data-status", data.error || "History refresh failed."); await loadData(); setText("#data-status", `History refreshed for ${data.snapshotDate}.`); }
  function exportData() { const payload = { exportedAt: new Date().toISOString(), account: { name: state.account?.name || "Brokerage", currency: "USD" }, holdings: state.holdings, quotes: state.quotes, snapshots: state.snapshots }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `mercury-brokerage-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setText("#data-status", state.preview ? "Sample export downloaded." : "Your private Brokerage export downloaded."); }
  async function showPreview() { state.preview = true; state.account = { id: "preview", name: "Sample Brokerage", weekly_contribution_cents: 50000 }; state.holdings = structuredClone(sampleHoldings); state.quotes = structuredClone(sampleQuotes); state.snapshots = structuredClone(sampleSnapshots); $("#workspace-mode").textContent = "Sample workspace"; $("#account-label").textContent = "Preview"; $("#brokerage-workspace").hidden = false; setText("#data-status", "Sample workspace — not synced. Configure Supabase to keep private data."); render(); }
  async function initialise() { try { const response = await fetch("/api/config", { cache: "no-store" }); const config = response.ok ? await response.json() : { configured: false }; if (!config.configured) return showPreview(); state.client = window.supabase.createClient(config.supabaseUrl, config.supabaseAnonKey); const { data: { session } } = await state.client.auth.getSession(); if (!session) { $("#auth-panel").hidden = false; $("#main-content").setAttribute("aria-busy", "false"); return; } state.user = session.user; state.account = await ensureAccount(); $("#account-label").textContent = state.user.email; $("#sign-out").hidden = false; $("#brokerage-workspace").hidden = false; await loadData(); setText("#data-status", "Private Brokerage account loaded."); } catch (error) { await showPreview(); setText("#data-status", `Private sync is unavailable: ${error.message}. Showing sample data only.`); } }
  $("#magic-link-form").addEventListener("submit", async (event) => { event.preventDefault(); const { error } = await state.client.auth.signInWithOtp({ email: $("#email").value, options: { emailRedirectTo: window.location.origin } }); setText("#auth-message", error ? error.message : "Check your email for a sign-in link."); });
  $("#account-trigger").addEventListener("click", () => { const menu = $("#account-menu"); menu.hidden = !menu.hidden; $("#account-trigger").setAttribute("aria-expanded", String(!menu.hidden)); }); $("#sign-out").addEventListener("click", async () => { await state.client.auth.signOut(); window.location.reload(); });
  $("#add-asset").addEventListener("click", () => openAsset(null)); $("#close-dialog").addEventListener("click", () => $("#asset-dialog").close()); $("#asset-form").addEventListener("submit", saveAsset); $("#lookup-quote").addEventListener("click", lookupQuote); $("#refresh-quotes").addEventListener("click", refreshPrices); $("#refresh-history").addEventListener("click", refreshHistory); $("#export-data").addEventListener("click", exportData); document.querySelectorAll('[name="valuationBasis"]').forEach((input) => input.addEventListener("change", toggleValuationFields));
  initialise();
})();
