"""Refresh the public FHFA county HPI snapshot; no dependencies or private data.
Run: python3 scripts/refresh-property-markets.py [downloaded-workbook.xlsx]
Review the generated diff and run npm run check before publishing.
"""
import datetime
import hashlib
import json
import pathlib
import re
import sys
import urllib.request
import zipfile
import io
import xml.etree.ElementTree as ET

URL = 'https://www.fhfa.gov/hpi/download/annual/hpi_at_county.xlsx'
raw = pathlib.Path(sys.argv[1]).read_bytes() if len(sys.argv) > 1 else urllib.request.urlopen(URL, timeout=40).read()
ns = {'m': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
with zipfile.ZipFile(io.BytesIO(raw)) as archive:
    strings = [''.join(s.itertext()) for s in ET.fromstring(archive.read('xl/sharedStrings.xml'))]
    rows = ET.fromstring(archive.read('xl/worksheets/sheet1.xml')).findall('.//m:row', ns)
    counties, latest, release = {}, 0, None
    for row in rows:
        cells = {}
        for cell in row:
            v = cell.find('m:v', ns)
            if v is not None:
                cells[re.sub(r'\d', '', cell.attrib['r'])] = strings[int(v.text)] if cell.attrib.get('t') == 's' else v.text
        if cells.get('A', '').startswith('Last updated:'):
            release = datetime.datetime.strptime(cells['A'].split(': ', 1)[1].rstrip('.'), '%B %d, %Y').date().isoformat()
        if not re.fullmatch(r'[A-Z]{2}', cells.get('A', '')) or not re.fullmatch(r'\d{5}', cells.get('C', '')):
            continue
        year = int(cells['D']); latest = max(year, latest)
        county = counties.setdefault(cells['C'], {'state': cells['A'], 'name': cells['B'], 'values': {}})
        try:
            value = float(cells.get('F', ''))
            if value > 0: county['values'][year] = value
        except ValueError:
            pass
    assert release and len(counties) > 2500 and latest >= 2024, 'Unexpected FHFA workbook; leave existing data unchanged.'
    # Require both endpoints in the same latest ten-year window. Never substitute
    # another county, older period, or a shorter window for missing observations.
    records = [{'fips': fips, 'state': c['state'], 'name': c['name'],
                'startIndex': c['values'].get(latest - 10), 'endIndex': c['values'].get(latest)}
               for fips, c in sorted(counties.items())]
    data = {'source': 'FHFA county All-Transactions HPI (developmental, NSA)', 'sourceUrl': URL,
            'released': release, 'retrieved': datetime.date.today().isoformat(),
            'workbookSha256': hashlib.sha256(raw).hexdigest(), 'startYear': latest - 10, 'endYear': latest, 'counties': records}
    target = pathlib.Path(__file__).resolve().parent.parent / 'data/property-markets.js'
    target.write_text('// Generated by scripts/refresh-property-markets.py from public FHFA data.\n'
                      '(function () { "use strict"; const markets = ' + json.dumps(data, separators=(',', ':')) + ';\n'
                      'if (typeof module !== "undefined") module.exports = markets;\n'
                      'if (typeof window !== "undefined") window.MercuryPropertyMarkets = markets;\n})();\n')
    index = target.parent.parent / 'index.html'
    index.write_text(re.sub(r'data/property-markets\.js\?v=[^\"]+', 'data/property-markets.js?v=' + data['workbookSha256'][:12], index.read_text()))
    print(f'{len(records)} counties; {latest - 10}–{latest}; released {release}; {sum(c["startIndex"] is not None and c["endIndex"] is not None for c in records)} complete windows')
